In [1]:
import tensorflow as tf
import numpy as np

In [2]:
# Predicting animal type based on various features
xy = np.loadtxt('./DeepLearningZeroToAll-master/data-04-zoo.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]
print(x_data.shape, y_data.shape)

(101, 16) (101, 1)


In [3]:
print(np.unique(y_data))
nb_classes = 7

[0. 1. 2. 3. 4. 5. 6.]


In [4]:
# Convert y_data to one_hot
y_one_hot = tf.keras.utils.to_categorical(y_data, nb_classes)
print("one_hot_shape:", y_one_hot.shape)
print("one_hot:", y_one_hot[:5])

one_hot_shape: (101, 7)
one_hot: [[1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]]


In [5]:
tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units=nb_classes, input_dim=16, activation='softmax'))
tf.model.compile(loss='categorical_crossentropy', optimizer=tf.keras.optimizers.SGD(lr=0.1), metrics=['accuracy'])
tf.model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 7)                 119       
Total params: 119
Trainable params: 119
Non-trainable params: 0
_________________________________________________________________


In [6]:
history = tf.model.fit(x_data, y_one_hot, epochs=100)

Epoch 1/100
4/4 [==============================] - 0s 1ms/step - loss: 1.9420 - accuracy: 0.3861
Epoch 2/100
4/4 [==============================] - 0s 2ms/step - loss: 1.6276 - accuracy: 0.4356
Epoch 3/100
4/4 [==============================] - 0s 2ms/step - loss: 1.4176 - accuracy: 0.5050
Epoch 4/100
4/4 [==============================] - 0s 7ms/step - loss: 1.3068 - accuracy: 0.5743
Epoch 5/100
4/4 [==============================] - 0s 2ms/step - loss: 1.1790 - accuracy: 0.5644
Epoch 6/100
4/4 [==============================] - 0s 1ms/step - loss: 1.0836 - accuracy: 0.6634
Epoch 7/100
4/4 [==============================] - 0s 3ms/step - loss: 0.9927 - accuracy: 0.7228
Epoch 8/100
4/4 [==============================] - 0s 3ms/step - loss: 0.9285 - accuracy: 0.7327
Epoch 9/100
4/4 [==============================] - 0s 3ms/step - loss: 0.8689 - accuracy: 0.7822
Epoch 10/100
4/4 [==============================] - 0s 3ms/step - loss: 0.8269 - accuracy: 0.8119
Epoch 11/100
4/4 [===========

In [7]:
# Single data test
test_data = np.array([[0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0]]) # expected prediction == 3 (feathers)
print('predict_proba:', tf.model.predict(test_data))
print('predict_class:', np.argmax(tf.model.predict(test_data), axis=-1))

predict_proba: [[9.9011976e-03 1.7931426e-02 4.8607502e-02 8.9248866e-01 1.4965377e-02
  4.1870706e-04 1.5687194e-02]]
predict_class: [3]


In [8]:
# Full x_data test
pred = tf.model.predict_classes(x_data)
for p, y in zip(pred, y_data.flatten()):
    print("[{}] Prediction: {} True Y: {}".format(p == int(y), p, int(y)))

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 1 True Y: 1
[True] Prediction: 3 True Y: 3
[True] Prediction: 6 True Y: 6
[True] Prediction: 6 True Y: 6
[True] Prediction: 6 True Y: 6
[True] Prediction: 1 True Y: 1
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 1 True Y: 1
[True] Predicti