In [1]:
import tensorflow as tf
import numpy as np

In [2]:
def min_max_scaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)

In [3]:
xy = np.array(
    [
        [828.659973, 833.450012, 908100, 828.349976, 831.659973],
        [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
        [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
        [816, 820.958984, 1008100, 815.48999, 819.23999],
        [819.359985, 823, 1188100, 818.469971, 818.97998],
        [819, 823, 1198100, 816, 820.450012],
        [811.700012, 815.25, 1098100, 809.780029, 813.669983],
        [809.51001, 816.659973, 1398100, 804.539978, 809.559998],
    ]
)

In [4]:
xy = min_max_scaler(xy)
print(xy)

[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]


In [5]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [10]:
tf.model = tf.keras.Sequential()
tf.model.add(tf.keras.layers.Dense(units=1, input_dim=4))
tf.model.add(tf.keras.layers.Activation('linear'))
tf.model.compile(loss='mse', optimizer=tf.keras.optimizers.SGD(lr=0.1))
tf.model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 1)                 5         
_________________________________________________________________
activation_1 (Activation)    (None, 1)                 0         
Total params: 5
Trainable params: 5
Non-trainable params: 0
_________________________________________________________________


In [11]:
history = tf.model.fit(x_data, y_data, epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 1ms/step - loss: 0.5065
Epoch 2/100
1/1 [==============================] - 0s 2ms/step - loss: 0.2461
Epoch 3/100
1/1 [==============================] - 0s 3ms/step - loss: 0.1434
Epoch 4/100
1/1 [==============================] - 0s 1ms/step - loss: 0.1013
Epoch 5/100
1/1 [==============================] - 0s 2ms/step - loss: 0.0823
Epoch 6/100
1/1 [==============================] - 0s 1ms/step - loss: 0.0725
Epoch 7/100
1/1 [==============================] - 0s 2ms/step - loss: 0.0662
Epoch 8/100
1/1 [==============================] - 0s 2ms/step - loss: 0.0615
Epoch 9/100
1/1 [==============================] - 0s 3ms/step - loss: 0.0575
Epoch 10/100
1/1 [==============================] - 0s 1ms/step - loss: 0.0540
Epoch 11/100
1/1 [==============================] - 0s 1ms/step - loss: 0.0508
Epoch 12/100
1/1 [==============================] - 0s 3ms/step - loss: 0.0477
Epoch 13/100
1/1 [==============================] - 0s 4ms/st

In [12]:
predictions = tf.model.predict(x_data)
print('Prediction:', predictions)

Prediction: [[0.96937597]
 [0.8238165 ]
 [0.6133761 ]
 [0.3344323 ]
 [0.55994993]
 [0.54690194]
 [0.16028586]
 [0.0450628 ]]


In [13]:
score = tf.model.evaluate(x_data, y_data)
print('Cost:', score)

1/1 [==============================] - 0s 1ms/step - loss: 0.0047
Cost: 0.004698371514678001
